'use strict';
const policy=require('./amenaza-execution-policy-v1_1.json');
const ORDER=policy.effective_scope_order;
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
function scopeOf(r){const t=clean(r.territory_class).toUpperCase(),s=clean(r.territorial_scope).toLowerCase();if(t==='LA_RIOJA'||s==='la rioja')return'La Rioja';if(t.startsWith('SPAIN_')||['españa','península','peninsula','región atlántica','region atlantica'].includes(s))return'España';if(t==='EUROPE_CONTINENTAL_OR_EU27'||s==='europe'||s==='europa')return'Europa';if(t==='GLOBAL'||s==='mundial'||s==='global')return'Mundial';if(t==='OTHER_EUROPEAN_COUNTRY'||t==='OTHER_EUROPEAN_SUBNATIONAL'||['country','sub_country'].includes(s))return'Subsidiario';return null}
function key(r){return [r.source_key||r.source,r.territorial_scope,r.category_system||r.normalized_system,r.source_reference||r.source_url||r.dataset_or_reference_identity].map(clean).join('||')}
function scoreScope(records){const by=new Map;for(const r of records){const n=Number(r.weighted_assessment_score);if(!Number.isFinite(n))continue;const k=key(r),old=by.get(k);if(!old||n>old.score)by.set(k,{score:n,record:r,conflict:!!old});else if(old&&n!==old.score)old.conflict=true}const arr=[...by.values()].sort((a,b)=>b.score-a.score);if(!arr.length)return null;const top=arr.slice(0,3),highest=top[0].score,mean=top.reduce((a,b)=>a+b.score,0)/top.length;return{score:Math.min(100,.8*highest+.2*mean),principal:top[0].record,logical_units:arr.length,conflict:arr.some(x=>x.conflict),selected:top.map(x=>x.record)}}
function execute({taxon,evidence_records=[],provider_score=null,scope_states={},conflict_taxon=false,updated_at=null}){const grouped=new Map(ORDER.map(x=>[x,[]]));for(const r of evidence_records){const s=scopeOf(r);if(s)grouped.get(s).push(r)}let effective=null,result=null;for(const s of ORDER){const z=scoreScope(grouped.get(s));if(z){effective=s;result=z;break}}const unresolved=clean(taxon?.overall_evidence_state).toUpperCase()==='TAXON_UNRESOLVED';const state=unresolved?'TAXON_UNRESOLVED':result?(conflict_taxon||result.conflict?'SCORED_WITH_CONFLICT':'SCORED'):'UNKNOWN';return{item_id:'STIMES.ITEM.AMENAZA',execution_policy:policy.policy_id,taxon:{...taxon},score_native_05:provider_score===''||provider_score==null?null:Number(provider_score),score_stimes_100:result?result.score:null,score_state:state,effective_scope:result?effective:null,scope_states:{...scope_states},selected_assessments:result?result.selected:[],principal_evidence:result?result.principal:null,evidence_records:[...evidence_records],reliability:{state:'PENDIENTE_DE_DEFINICION',numeric_value:null,category:null},updated_at,cache_reused:true,external_query_performed:false}}
module.exports={policy,scopeOf,scoreScope,execute};
