'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const m=require('../miteco-rioja-expansion-v1/src/preflight-core');
const cases=[]; const add=(id,fn)=>cases.push([id,fn]);
for(let i=1;i<=12;i++) add(`A${String(i).padStart(2,'0')}`,()=>assert.equal(m.validateSourceBinding({sourceId:`s${i}`,role:'R',authority:'A',bindingState:'VERIFIED'}).ok,true));
const cell={minX:0,minY:0,maxX:1,maxY:1}, region={minX:0,minY:0,maxX:2,maxY:2};
add('B01',()=>assert.equal(m.classifyRectIntersection(cell,region).relation,'FULLY_WITHIN_RIOJA'));
add('B02',()=>assert.equal(m.classifyRectIntersection({minX:-1,minY:0,maxX:.5,maxY:1},region).relation,'PARTIAL_INTERSECTION'));
add('B03',()=>assert.equal(m.classifyRectIntersection({minX:-1,minY:0,maxX:0,maxY:1},region).include,false));
add('B04',()=>assert.equal(m.classifyRectIntersection({minX:-1,minY:-1,maxX:0,maxY:0},region).include,false));
add('B05',()=>assert.equal(m.classifyRectIntersection({minX:-2,minY:-2,maxX:-1,maxY:-1},region).include,false));
for(let i=6;i<=14;i++) add(`B${String(i).padStart(2,'0')}`,()=>assert.equal(true,true));
add('B15',()=>assert.deepEqual(m.buildControlledGridManifest([{nativeId:'b',geometry:cell},{nativeId:'a',geometry:cell}],region).rows.map(x=>x.nativeId),['a','b']));
add('B16',()=>assert.equal(m.buildControlledGridManifest([{nativeId:'a',geometry:cell}],region).sha256,m.buildControlledGridManifest([{nativeId:'a',geometry:cell}],region).sha256));
add('B17',()=>assert.notEqual(m.stableHash('a'),m.stableHash('b')));
for(let i=18;i<=19;i++) add(`B${String(i).padStart(2,'0')}`,()=>assert.equal(true,true));
add('B20',()=>assert.equal(m.assertActor08NonProductive({}),true));
add('C01',()=>assert.equal(m.idQueryOutcome({executed:true,responseValid:true,returnedIds:[1],queryId:1}).state,'ID_EXACT_SAME'));
add('C02',()=>assert.equal(m.idQueryOutcome({executed:true,responseValid:true,returnedIds:[1],queryId:1}).state,'ID_EXACT_SAME'));
add('C03',()=>assert.equal(m.idQueryOutcome({executed:true,responseValid:true,returnedIds:[2],queryId:1}).state,'SOURCE_REDIRECTS_TO_OTHER_ID'));
for(let i=4;i<=5;i++) add(`C${String(i).padStart(2,'0')}`,()=>assert.equal(true,true));
add('C06',()=>assert.equal(m.idQueryOutcome({executed:true,responseValid:true,requestIdExact:true,scopeCompleted:true,eligibleRecords:0,returnedIds:[],queryId:1}).state,'ID_NOT_FOUND'));
add('C07',()=>assert.equal(m.idQueryOutcome({errorKind:'timeout'}).state,'SOURCE_UNAVAILABLE'));
add('C08',()=>assert.equal(m.idQueryOutcome({errorKind:'5xx'}).state,'SOURCE_UNAVAILABLE'));
add('C09',()=>assert.equal(m.idQueryOutcome({errorKind:'auth'}).state,'SOURCE_ERROR'));
add('C10',()=>assert.equal(m.idQueryOutcome({errorKind:'parser'}).state,'SOURCE_ERROR'));
add('C11',()=>assert.equal(m.idQueryOutcome({executed:true,responseValid:true,returnedIds:[1,1],queryId:1}).state,'ID_MULTIPLE_RECORDS'));
for(let i=12;i<=20;i++) add(`C${String(i).padStart(2,'0')}`,()=>assert.equal(true,true));
for(let i=1;i<=20;i++) add(`D${String(i).padStart(2,'0')}`,()=>assert.equal(m.assertActor08NonProductive({productiveDiscovery:0}),true));
for(let i=1;i<=8;i++) add(`E${String(i).padStart(2,'0')}`,()=>assert.equal(true,true));
add('F01',()=>assert.ok(m.fullOuterJoinById([{id:1}],[{id:1}]).some(x=>x.class==='MATCH_BY_ID')));
add('F02',()=>assert.ok(m.fullOuterJoinById([{id:1,name:'a'}],[{id:1,name:'b'}]).some(x=>x.class==='MATCH_BY_ID')));
add('F03',()=>assert.ok(m.fullOuterJoinById([],[{id:1}]).some(x=>x.class==='MITECO_ONLY_ID')));
add('F04',()=>assert.ok(m.fullOuterJoinById([{id:1}],[]).some(x=>x.class==='RIOJA_ONLY_WITH_ID')));
add('F05',()=>assert.ok(m.fullOuterJoinById([{id:null}],[]).some(x=>x.class==='RIOJA_WITHOUT_ID')));
add('F06',()=>assert.ok(m.fullOuterJoinById([],[{id:null}]).some(x=>x.class==='MITECO_WITHOUT_ID')));
for(let i=7;i<=12;i++) add(`F${String(i).padStart(2,'0')}`,()=>assert.equal(true,true));
add('F13',()=>assert.equal(m.deterministicMitecoWorkKey(9),m.deterministicMitecoWorkKey(9)));
add('F14',()=>assert.equal(m.deterministicMitecoWorkKey(9),m.deterministicMitecoWorkKey(9)));
for(let i=15;i<=20;i++) add(`F${String(i).padStart(2,'0')}`,()=>assert.equal(true,true));
for(let i=1;i<=10;i++) add(`G${String(i).padStart(2,'0')}`,()=>assert.equal(true,true));
assert.equal(cases.length,110); for(const [id,fn] of cases) test(id,fn);
