'use strict';

const equivalence = require('../contracts/proteccion-category-equivalence-v2.json');
const MAP = new Map(equivalence.entries.map(e => [e.category_class, e]));
const APPLICABLE = new Set(['APPLICABLE_LA_RIOJA','APPLICABLE_NATIONAL','APPLICABLE_EU','APPLICABLE_INTERNATIONAL']);
const EFFECTIVE_MAPPING_STATES = new Set(['ACTIVE_WHEN_PRIMARY_LAW_VERIFIED','ACTIVE_WHEN_PRIMARY_LAW_AND_TAXON_ANNEX_VERIFIED','ACTIVE_WHEN_PRIMARY_LAW_TAXON_AND_SITE_VERIFIED','SOURCE_DEPENDENT_PRIMARY_VERIFICATION_REQUIRED']);
const NON_PROTECTIVE_MAPPING_STATES = new Set(['CONTEXT_ONLY_NOT_EFFECTIVE_PROTECTION','HISTORICAL_OR_CONTEXT_ONLY_NOT_EFFECTIVE_CURRENT_PROTECTION']);
function text(v){return String(v==null?'':v).trim()}
function fold(v){return text(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase()}
function clone(v){return JSON.parse(JSON.stringify(v))}
function resolveApplicability(r){const sub=fold(r.sub_country||r.autonomous_community),j=fold(r.jurisdiction_name),s=fold(r.jurisdiction_level||r.territorial_scope||r.scope_normalized),auto=s.includes('AUTONOM')||fold(r.jurisdiction_level).includes('AUTONOM');if(sub)return sub.includes('LA RIOJA')?'APPLICABLE_LA_RIOJA':'EXTERNAL_AUTONOMOUS_REFERENCE';if(auto){if(j.includes('LA RIOJA'))return'APPLICABLE_LA_RIOJA';if(j)return'EXTERNAL_AUTONOMOUS_REFERENCE';return'UNKNOWN_JURISDICTION'}if(s.includes('LA RIOJA')||j.includes('LA RIOJA'))return'APPLICABLE_LA_RIOJA';if(s.includes('NACIONAL')||s.includes('SPAIN')||s.includes('ESPANA')||s.includes('STATE')||j==='ESPANA'||j==='SPAIN')return'APPLICABLE_NATIONAL';if(s.includes('EUROPE')||s==='EU'||s.includes('UNION EUROPEA')||j==='EU'||j.includes('UNION EUROPEA'))return'APPLICABLE_EU';if(s.includes('INTERNACIONAL')||s.includes('INTERNATIONAL')||s.includes('GLOBAL')||j.includes('INTERNACIONAL')||j.includes('INTERNATIONAL'))return'APPLICABLE_INTERNATIONAL';return'UNKNOWN_JURISDICTION'}
function resolveCurrentness(r){if(r.currentness_verified!==true)return'CURRENTNESS_NOT_VERIFIED';const s=fold(r.currentness_status||r.source_currentness);if(['CURRENT','SOURCE_MARKED_CURRENT','VIGENTE'].includes(s))return'CURRENT_VERIFIED';if(['NOT_CURRENT','SOURCE_MARKED_NOT_CURRENT','DEROGADA','DEROGADO','SUPERSEDED','REPEALED'].includes(s))return'NOT_CURRENT_VERIFIED';return'CURRENTNESS_UNKNOWN'}
function literalGuardSatisfied(r,m){if(!m||!m.literal_guard)return true;const l=fold(r.original_category||r.annex_or_list);if(m.literal_guard==='CITES_A_OR_APPENDIX_I_V1'){if(l.includes('APENDICE II')||l.includes('APPENDIX II')||l.includes('ANEXO B')||l.includes('ANNEX B'))return false;return l.includes('APENDICE I')||l.includes('APPENDIX I')||l.includes('ANEXO A')||l.includes('ANNEX A')}if(m.literal_guard==='CITES_B_OR_APPENDIX_II_V1')return l.includes('APENDICE II')||l.includes('APPENDIX II')||l.includes('ANEXO B')||l.includes('ANNEX B');if(m.literal_guard==='CITES_D_V1')return l.includes('ANEXO D')||l.includes('ANNEX D');return false}
function normalizeRecord(r){const z=clone(r),m=MAP.get(r.category_class);z.applicability_resolution=resolveApplicability(r);z.currentness_resolution=resolveCurrentness(r);z.equivalence_version=equivalence.table_id;z.mapping_state=m?m.effective_eligibility:'NO_EQUIVALENCE_FOUND';z.score_native_05_category=m&&typeof m.source_model_score_100==='number'?m.source_model_score_100:null;z.score_100_from_equivalence=m&&typeof m.effective_score_100==='number'?m.effective_score_100:null;z.literal_guard_satisfied=literalGuardSatisfied(r,m);return z}
function isTaxonResolved(r){return r.taxon_resolved===true||['RESOLVED','ACCEPTED_IDENTITY_RESOLVED','VALIDATED'].includes(fold(r.taxonomic_state))}
function baseLegalRecord(r){return r.evidence_state==='VALID_SOURCE_EVIDENCE'&&isTaxonResolved(r)&&r.source_authorized===true&&r.primary_source_verified===true&&r.legal_validity_verified===true&&r.currentness_resolution==='CURRENT_VERIFIED'&&r.legal_applicability_verified===true&&APPLICABLE.has(r.applicability_resolution)}
function mappingGuardsSatisfied(r){if(!EFFECTIVE_MAPPING_STATES.has(r.mapping_state)||!r.literal_guard_satisfied)return false;if(r.mapping_state==='SOURCE_DEPENDENT_PRIMARY_VERIFICATION_REQUIRED'&&r.category_equivalence_verified!==true)return false;if(r.mapping_state==='ACTIVE_WHEN_PRIMARY_LAW_AND_TAXON_ANNEX_VERIFIED'&&r.taxon_annex_membership_verified!==true)return false;if(r.mapping_state==='ACTIVE_WHEN_PRIMARY_LAW_TAXON_AND_SITE_VERIFIED'&&(r.taxon_annex_membership_verified!==true||r.site_applicability_verified!==true))return false;return true}
function isEffectiveCandidate(r){return baseLegalRecord(r)&&mappingGuardsSatisfied(r)&&typeof r.score_100_from_equivalence==='number'}
function potentiallyProtectiveButUnresolved(r){if(!baseLegalRecord(r)||NON_PROTECTIVE_MAPPING_STATES.has(r.mapping_state))return false;if(r.mapping_state==='NO_EQUIVALENCE_FOUND')return true;return!isEffectiveCandidate(r)}
function materialConflict(rs){return rs.some(r=>r.conflict_unresolved===true&&baseLegalRecord(r))}
function searchIsComplete(s){return!!s&&s.query_executed===true&&s.taxon_resolved===true&&s.authorized_source_set_verified===true&&s.all_authorized_sources_consulted===true&&s.primary_source_checks_complete===true&&s.source_not_acquired!==true}
function unresolvedState(rs,s){if(rs.some(r=>!isTaxonResolved(r))||(s&&s.taxon_resolved===false))return'TAXON_UNRESOLVED';if(s&&s.source_not_acquired===true)return'SOURCE_NOT_ACQUIRED';if(materialConflict(rs))return'CONFLICT';if(rs.some(potentiallyProtectiveButUnresolved))return'UNKNOWN';if(!searchIsComplete(s))return'NO_COMPROBADO';return'UNKNOWN'}
function selectProtection({taxon,evidence=[],search={},downstreamRequiresNumber=false,updatedAt=null}){if(!taxon||!(taxon.taxon_id||taxon.release_row_id||taxon.taxon_identifier))throw new Error('PROTECCION_REQUIRES_TAXON_ID');if(evidence.some(r=>Object.prototype.hasOwnProperty.call(r,'manual_score')))throw new Error('MANUAL_PROTECTION_SCORE_PROHIBITED');const normalized=evidence.map(normalizeRecord),candidates=normalized.filter(isEffectiveCandidate).sort((a,b)=>b.score_100_from_equivalence-a.score_100_from_equivalence),conflict=materialConflict(normalized),blockedPotential=normalized.some(potentiallyProtectiveButUnresolved);let state,score100=null,effective=[];if(conflict)state='CONFLICT';else if(candidates.length){score100=candidates[0].score_100_from_equivalence;effective=candidates.filter(r=>r.score_100_from_equivalence===score100);state='PROTECTED'}else if(searchIsComplete(search)&&!blockedPotential){state='SIN_PROTECCION_LEGAL';score100=0}else state=unresolvedState(normalized,search);const placeholder=score100==null&&downstreamRequiresNumber===true;return{semantic_state:state,state,score_100:score100,score_numeric_projection_100:placeholder?0:score100,score_numeric_projection_is_placeholder:placeholder,score_numeric_projection_semantics:placeholder?'TECHNICAL_NON_SEMANTIC_NON_PONDERING':(score100==null?null:'EVALUABLE_SCORE'),numeric_projection_rule:placeholder?'EXPLICIT_CONTRACT_PLACEHOLDER':null,score_native_05:search.score_native_05==null?null:search.score_native_05,equivalence_version:equivalence.table_id,selected_effective_evidence:clone(effective),normalized_evidence:clone(normalized),original_evidence:clone(evidence),updated_at:updatedAt,reliability:{state:'PENDIENTE_DE_DEFINICION',numeric_value:null,category:null},provenance:{evidence_count:evidence.length,search_complete:searchIsComplete(search)},cacheable:false}}
module.exports={equivalence,resolveApplicability,resolveCurrentness,normalizeRecord,isEffectiveCandidate,searchIsComplete,selectProtection};
