const { test, expect } = require('@playwright/test');
const baseURL=process.env.MVP_BASE_URL||'http://127.0.0.1:3000';
const REF_EDITED='JBLR STAGING · Referencia bibliográfica demo MVP6 · editada';
const ASSERT_EDITED='JBLR STAGING · afirmación sintética MVP6 · editada · no constituye conclusión científica';
async function openPlantago(page){await page.goto(baseURL);await page.getByLabel('Buscar por nombre científico').fill('Plantago');await page.getByRole('button',{name:'Buscar'}).click();await page.getByText('Plantago major L.',{exact:true}).click();await expect(page.getByRole('button',{name:'BIBLIOGRAFÍA / EVIDENCIA'})).toBeVisible();}
async function openEvidence(page){await page.getByRole('button',{name:'BIBLIOGRAFÍA / EVIDENCIA'}).click();await expect(page.locator('#taxonEvidenceStatus')).not.toHaveText('Cargando…');await expect(page.locator('#taxonEvidenceView')).toContainText('REFERENCE ≠ ASSERTION');}
async function createOrReuseReference(page){await page.getByRole('button',{name:'Crear / reutilizar referencia'}).click();await expect(page.locator('#referenceTitle')).toHaveValue(/^JBLR STAGING ·/);await page.locator('#referenceCreateDialog').getByRole('button',{name:'Crear / reutilizar'}).click();await expect(page.locator('#referenceCreateDialog')).not.toBeVisible();await expect(page.locator('#referenceList .reference-card')).toHaveCount(1);}
async function createOrReuseAssertion(page){await page.getByRole('button',{name:'Crear / reutilizar Assertion'}).click();await expect(page.locator('#assertionStatement')).toHaveValue(/no constituye conclusión científica/);await page.locator('#assertionCreateDialog').getByRole('button',{name:'Crear / reutilizar'}).click();await expect(page.locator('#assertionCreateDialog')).not.toBeVisible();await expect(page.locator('#assertionList .assertion-card')).toHaveCount(1);await expect(page.locator('#assertionList .assertion-card')).toContainText('unresolved');}
async function ensureLinked(page){await page.getByRole('button',{name:'Vincular soporte'}).click();await expect(page.locator('#assertionDetail')).toContainText('AFIRMACIÓN');await expect(page.locator('#assertionDetail')).toContainText('unresolved');await expect(page.locator('#assertionDetail .assertion-evidence-card')).toHaveCount(1);await expect(page.locator('#assertionDetail .assertion-evidence-card')).toContainText('supports');await expect(page.locator('#assertionDetail')).toContainText('supports no equivale a conclusión');}
test.describe.serial('MVP_PRODUCTIVO_6 bibliography and scientific evidence',()=>{
 test('creates/reuses Reference, Assertion and EvidenceLink, edits safely and persists',async({page})=>{
  await openPlantago(page);await openEvidence(page);await createOrReuseReference(page);await createOrReuseAssertion(page);await ensureLinked(page);
  const subject=await page.locator('#assertionDetail .resource-id').nth(1).innerText();expect(subject).toMatch(/^Subject resource: /);
  await page.locator('#assertionDetail .assertion-evidence-card').click();await expect(page.locator('#referenceDetail')).toContainText('REFERENCIA BIBLIOGRÁFICA');await expect(page.locator('#referenceDetail')).toContainText('DOI: NULL');await expect(page.locator('#referenceDetail')).toContainText('ISBN: NULL');
  if((await page.locator('#referenceDetail h1').innerText())!==REF_EDITED){await page.getByRole('button',{name:'Editar referencia'}).click();await page.locator('#referenceEditTitle').fill(REF_EDITED);await page.locator('#referenceEditNotes').fill('referencia bibliográfica demo MVP6 · editada');await page.locator('#referenceEditDialog').getByRole('button',{name:'Guardar cambios'}).click();await expect(page.locator('#referenceEditDialog')).not.toBeVisible();}
  await expect(page.locator('#referenceDetail h1')).toHaveText(REF_EDITED);await page.getByRole('button',{name:'Volver a Assertion'}).click();await expect(page.locator('#assertionDetail')).toContainText('unresolved');
  if((await page.locator('#assertionDetail h1').innerText())!==ASSERT_EDITED){await page.getByRole('button',{name:'Editar Assertion'}).click();await page.locator('#assertionEditStatement').fill(ASSERT_EDITED);await page.locator('#assertionEditNotes').fill('afirmación sintética demo MVP6 · editada');await page.locator('#assertionEditDialog').getByRole('button',{name:'Guardar cambios'}).click();await expect(page.locator('#assertionEditDialog')).not.toBeVisible();}
  await expect(page.locator('#assertionDetail h1')).toHaveText(ASSERT_EDITED);await expect(page.locator('#assertionDetail')).toContainText('unresolved');
  await page.reload();await openPlantago(page);await openEvidence(page);await expect(page.locator('#assertionList .assertion-card')).toHaveCount(1);await expect(page.locator('#referenceList .reference-card')).toHaveCount(1);await expect(page.locator('#assertionList .assertion-card')).toContainText(ASSERT_EDITED);await page.locator('#assertionList .assertion-card').click();await expect(page.locator('#assertionDetail')).toContainText('supports');await page.locator('#assertionDetail .assertion-evidence-card').click();await expect(page.locator('#referenceDetail h1')).toHaveText(REF_EDITED);await page.screenshot({path:'evidence/mvp6-evidence-desktop.png',fullPage:true});
 });
 test.describe('mobile evidence UI',()=>{test.use({viewport:{width:390,height:844}});test('TaxonConcept to Assertion to Reference remains usable without horizontal overflow',async({page})=>{
  await openPlantago(page);await openEvidence(page);await expect(page.locator('#assertionList .assertion-card')).toHaveCount(1);await page.locator('#assertionList .assertion-card').click();await expect(page.locator('#assertionDetail')).toContainText('unresolved');await page.locator('#assertionDetail .assertion-evidence-card').click();await expect(page.locator('#referenceDetail')).toContainText('REFERENCIA BIBLIOGRÁFICA');let overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);expect(overflow).toBe(false);await page.getByRole('button',{name:'Editar referencia'}).click();await expect(page.locator('#referenceEditTitle')).toBeVisible();await page.locator('#cancelReferenceEditBtn').click();await page.getByRole('button',{name:'Volver a Assertion'}).click();await page.getByRole('button',{name:'Editar Assertion'}).click();await expect(page.locator('#assertionEditStatement')).toBeVisible();await page.locator('#cancelAssertionEditBtn').click();overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);expect(overflow).toBe(false);await page.screenshot({path:'evidence/mvp6-evidence-mobile.png',fullPage:true});
 });});
});
