const { test, expect } = require('@playwright/test');

const baseURL = process.env.MVP_BASE_URL || 'http://127.0.0.1:3000';
const POPULATION_BASE='JBLR STAGING · Población demo MVP2';
const POPULATION_EDITED='JBLR STAGING · Población demo MVP2 · editada';
const VISIT_BASE='JBLR STAGING · Visita demo MVP3';
const VISIT_EDITED='JBLR STAGING · Visita demo MVP3 · editada';
const INDIVIDUAL_BASE='JBLR STAGING · Madre demo MVP8';
const INDIVIDUAL_EDITED='JBLR STAGING · Madre demo MVP8 · editada';

async function openPlantago(page){await page.goto(baseURL);await page.getByLabel('Buscar por nombre científico').fill('Plantago');await page.getByRole('button',{name:'Buscar'}).click();await expect(page.getByText('Plantago major L.',{exact:true})).toBeVisible();await page.getByText('Plantago major L.',{exact:true}).click();await expect(page.getByRole('heading',{name:'Taxonomía'})).toBeVisible();}
async function openPopulation(page){await openPlantago(page);await page.getByRole('button',{name:/^Poblaciones:/}).click();await expect(page.locator('#populationsStatus')).not.toHaveText('Cargando…');const list=page.locator('#populationList');let p=list.getByText(POPULATION_EDITED,{exact:true});if(!(await p.count()))p=list.getByText(POPULATION_BASE,{exact:true});await p.click();await expect(page.locator('#populationDetail').getByRole('heading',{name:'POBLACIÓN'})).toBeVisible();await expect(page.getByRole('button',{name:'INDIVIDUOS'})).toBeVisible();}
async function openVisit(page){await page.getByRole('button',{name:'Prospecciones / visitas'}).click();await expect(page.locator('#fieldActivityStatus')).not.toHaveText('Cargando…');const list=page.locator('#fieldVisitList');let v=list.getByText(VISIT_EDITED,{exact:true});if(!(await v.count()))v=list.getByText(VISIT_BASE,{exact:true});await v.click();await expect(page.locator('#fieldVisitDetail').getByRole('heading',{name:'VISITA DE CAMPO'})).toBeVisible();}
async function openCollection(page){await page.getByRole('button',{name:'Recolección / material'}).click();await expect(page.locator('#materialFlowStatus')).not.toHaveText('Cargando…');await page.locator('#collectionEventList .collection-card').first().click();await expect(page.locator('#mvp8CollectionIndividualsSection')).toBeVisible();}
async function openSample(page){await page.locator('#collectionEventDetail .sample-card').first().click();await expect(page.locator('#mvp8SampleOriginSection')).toBeVisible();await expect(page.locator('#mvp8SampleOriginSection')).not.toContainText('Cargando trazabilidad…');}

async function ensureIndividual(page){
  await page.getByRole('button',{name:'INDIVIDUOS'}).click();await expect(page.locator('#individualsStatus')).not.toHaveText('Cargando…');
  if(!(await page.locator('#individualList .individual-card').count())){await page.getByRole('button',{name:'Crear / reutilizar Individual'}).click();await page.locator('#individualCreateDialog').getByRole('button',{name:'Crear / reutilizar'}).click();await expect(page.locator('#individualCreateDialog')).not.toBeVisible();}
  await expect(page.locator('#individualList .individual-card')).toHaveCount(1);await page.locator('#individualList .individual-card').click();await expect(page.locator('#individualDetail')).toContainText('JBLR-POP-00000013');await expect(page.locator('#individualDetail')).toContainText('Plantago major L.');
  if(await page.locator('#individualDetail h1').getByText(INDIVIDUAL_BASE,{exact:true}).count()){await page.getByRole('button',{name:'Editar Individual'}).click();await page.locator('#individualEditLabel').fill(INDIVIDUAL_EDITED);await page.locator('#individualEditNotes').fill('madre demo MVP8 · editada; no representa una planta real');await page.locator('#individualEditDialog').getByRole('button',{name:'Guardar cambios'}).click();await expect(page.locator('#individualEditDialog')).not.toBeVisible();}
  await expect(page.locator('#individualDetail h1')).toHaveText(INDIVIDUAL_EDITED);await page.locator('#backFromIndividualBtn').click();await expect(page.locator('#populationDetail')).toBeVisible();
}

test.describe.serial('MVP_PRODUCTIVO_8 individual and mother traceability',()=>{
  test('creates/reuses Individual, links CollectionIndividual and complements SampleOrigin',async({page})=>{
    await openPopulation(page);await ensureIndividual(page);await openVisit(page);await openCollection(page);
    await page.getByRole('button',{name:'Gestionar individuos / madres'}).click();await expect(page.locator('#collectionIndividualsStatus')).not.toHaveText('Cargando…');
    if(!(await page.locator('#collectionIndividualList .collection-individual-card').count())){await page.getByRole('button',{name:'Añadir / reutilizar vínculo'}).click();}
    await expect(page.locator('#collectionIndividualList .collection-individual-card')).toHaveCount(1);await expect(page.locator('#collectionIndividualList')).toContainText('mother_plant');await expect(page.locator('#collectionIndividualList')).toContainText('secuencia 1');
    await page.locator('#collectionIndividualList .collection-individual-card').click();await expect(page.locator('#individualDetail')).toContainText('JBLR-POP-00000013');await page.locator('#backFromIndividualBtn').click();await page.locator('#backCollectionIndividualsBtn').click();
    await openSample(page);await expect(page.locator('#mvp8SampleOriginSection')).toContainText('JBLR-COL-00000017');
    if(await page.getByRole('button',{name:'Asociar / reutilizar Individual'}).count())await page.getByRole('button',{name:'Asociar / reutilizar Individual'}).click();
    await expect(page.locator('#mvp8SampleOriginSection')).toContainText(INDIVIDUAL_EDITED);await expect(page.locator('#mvp8SampleOriginSection')).toContainText('SampleOrigin conserva simultáneamente CollectionEvent + Individual.');
    await page.locator('#mvp8SampleOriginSection').getByRole('button',{name:/Abrir Individual/}).click();await expect(page.locator('#individualDetail')).toContainText('JBLR-POP-00000013');await expect(page.locator('#individualDetail')).toContainText('1 CollectionIndividual · 1 SampleOrigin');
    await page.reload();await openPopulation(page);await page.getByRole('button',{name:'INDIVIDUOS'}).click();await expect(page.locator('#individualList .individual-card')).toHaveCount(1);await expect(page.locator('#individualList')).toContainText(INDIVIDUAL_EDITED);await page.locator('#backIndividualsToPopulationBtn').click();await openVisit(page);await openCollection(page);await page.getByRole('button',{name:'Gestionar individuos / madres'}).click();await expect(page.locator('#collectionIndividualList .collection-individual-card')).toHaveCount(1);await page.locator('#backCollectionIndividualsBtn').click();await openSample(page);await expect(page.locator('#mvp8SampleOriginSection')).toContainText('JBLR-COL-00000017');await expect(page.locator('#mvp8SampleOriginSection')).toContainText(INDIVIDUAL_EDITED);await page.screenshot({path:'evidence/mvp8-individual-traceability-desktop.png',fullPage:true});
  });

  test.describe('mobile individual UI',()=>{test.use({viewport:{width:390,height:844}});test('Population, CollectionEvent and Sample trace remain usable without horizontal overflow',async({page})=>{
    await openPopulation(page);await page.getByRole('button',{name:'INDIVIDUOS'}).click();await expect(page.locator('#individualList .individual-card')).toHaveCount(1);await page.locator('#individualList .individual-card').click();await page.getByRole('button',{name:'Editar Individual'}).click();await expect(page.locator('#individualEditLabel')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)).toBe(false);await page.locator('#cancelIndividualEditBtn').click();await page.locator('#backFromIndividualBtn').click();await openVisit(page);await openCollection(page);await page.getByRole('button',{name:'Gestionar individuos / madres'}).click();await expect(page.locator('#collectionIndividualList .collection-individual-card')).toHaveCount(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)).toBe(false);await page.locator('#backCollectionIndividualsBtn').click();await openSample(page);await expect(page.locator('#mvp8SampleOriginSection')).toContainText(INDIVIDUAL_EDITED);expect(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)).toBe(false);await page.screenshot({path:'evidence/mvp8-individual-traceability-mobile.png',fullPage:true});});});
});
